spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/test
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        ddl-auto: false
    generate-ddl: false
springdoc:
  version: '@springdoc.version@'
server:
  error:
    include-stacktrace: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
    logfile:
      external_file: logfile.log
logging:
  level:
    root: info
  file:
    name: logfile.log
